name: MyFirstWorkflow

on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello GitHubactions"

      - name: Checkout
        uses: actions/checkout@4.2.2
      - name: List files in  repository
        run: |
          echo "The repository ${{github.repository}} contains the following files:"
          tree
    
     

  
